### ISSUE TITLE
장고 MVC 흐름 대충 정리

### ISSUE THREAD

**Issue by ii200400** [sovovy/comnet_giester#1]
client가 주소를 입력하게되어 접속하면 일어나는 순서대로 써보겠다.
아래의 주소들은 우리의 giester프로젝트를 기준으로하는 주소이다.

1)giester\urls 파일

client가 접속한 주소에 따른 담당자를 정한다.
(우리같은 프로젝트같은)간단한 홈페이지의 경우 

url(r'^admin/', admin.site.urls), #주소:localhost:8000/admin, 장고 어드민을 담당으로 지정
url(r'^', include('파일경로(manage.py기준)'))   #주소:localhost:8000/...우리가 만든 파일(앱)을 담당으로 지정 

위의 형식을 갖는다.
참고로 include는 앱에 접근하기 위해 필요한 문법이라고 한다.

2)game\urls 파일

위의 giester\urls 파일에서 이 파일을 담당으로 지정해주면
또다시 주소를 통해서 세부적으로 담당자를 정한다.
위와같이 url(r'^.../...+!?$',view.담당할 함수이름)과 같은 형식의 코드가 들어가게 된다.
              (위는 정규표현식으로 주소를 표현한 것을 대충 써놓은것)
이후에 그러면 gmae\view.py의 함수가 위의 코드에 따라서 호출된다.

3)gmae\view.py 파일
(DB에 저장되어있는 정보들에 관해서는 아래서 다루니 일단 읽자)
호출이 되면 DB에 미리 저장되어있는 정보를 요리하는 역할을 하는 파일이다.
일반적으로는 (잘모르겠지만) DB에서 받은 정보를 예외처리도하고 쓰기 좋은 형태로 만들어서
game\templates\game의 html로 정보를 보내준다.

view파일에서 DB에 저장되어있는 정보들을 가져오기 위한 많은 문법들이 있는데 기본적으로 모르겟다.핳

4)game\templates\game~~.html들
gmae\view.py에서 받은 내용을 client에게 보여주는 열할을 한다.
위에서도 볼 수 있듯이 html형식을 하고있으며 나로써는 알 수 없는 부분뿐이다.
http://www.w3schools.com/ 
위의 홈페이지에서 html에 관해서 쉽게 설명하고있으니 참고하자.

5)game\models.py 파일
DB에 정보를 저장하기 위해서 정의해주는(정의라고 해야할지 선언이라고 해야할지 잘 모르겠다.) 파일이다.
model의 class는 model.Model을 상속받아야 쓸수 있는 것 같다.
모델 안의 맴버변수의 정보는 여러가지 Fieldtype(int형 같은건가;;)을 가진다.

우리의 프로젝트의 경우에는 6.2일 기준으로 이름이 Player이라는 클래스에
이름이 10글자인플레이어 두명과
po = models.CharField(max_length=10, default='')
pt = models.CharField(max_length=10, default='')

누구의 턴인지 보여주는 turn과
turn = models.CharField(max_length=3, default='00')

맵을 의미하는 cont가 있다.
cont = models.TextField(default='033330\n044440\n000000\n000000\n011110\n022220')

고칠 부분이 있으면 의견주세요~

**Comment by sovovy** [comment]
아 board인줄 알았는데 cont였네
그리고 cont defualt값에 \n은 없어도 될 것 같아서 뺀다고 했는데 그것도 안 빼놨었군 하핳
근데 cont 이름은 그대로 cont로 할까 board로 바꿀까??

**Comment by ii200400** [comment]
후훗 이미 적용했지
