### ISSUE TITLE
board의 값에 대해서

### ISSUE THREAD

**Issue by sovovy** [sovovy/comnet_giester#2]
원래 정의는
0 - 빈칸
1 - 1P의 파란 패
2 - 1P의 빨간 패
3 - 2P의 파란 패
4 - 2P의 빨간 패

였는데 방금 game.html에서 맵핑한걸 띄우다가
출구를 띄우기 위해 숫자를 더 추가하면 좋을 것 같아서
8 - 오른쪽 출구
9 - 왼쪽 출구
를 추가했습니다.

board의 default값도 바꿔둘게요~!

**Comment by ii200400** [comment]
음..! 원래 있는건줄 알았는데.. 자연스러웠다
